name: mpw
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.15.0 <3.0.0'

dependencies: 
  flutter_swipe_action_cell: ^2.1.6
  cupertino_icons: ^1.0.2
  get: 4.6.1
  flutter: 
    sdk: flutter
  ffi: ^1.0.0
  path: ^1.8.0
  markdown: ^4.0.1
  flutter_markdown: ^0.6.9
  # 存储与读取
  shared_preferences: ^2.0.12
  encrypt: ^ 5.0.1
dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - doc/
    - doc/assets/

